# Generated by Django 5.1.7 on 2025-04-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalAttendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='course_code',
            field=models.TextField(blank=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(choices=[('ML', 'Machine Learning'), ('AI', 'Artificial Intelligence'), ('DS', 'Data Science')], max_length=20),
        ),
    ]
