# Generated by Django 5.1.7 on 2025-04-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0002_alter_student_user'),
        ('teacherapp', '0003_remove_teacher_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='students', to='teacherapp.teacher'),
        ),
    ]
