# Generated by Django 5.1.7 on 2025-04-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AttendanceSystem', '0002_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='en_Number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
