# Generated by Django 5.1.7 on 2025-04-14 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0002_teacher_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subject',
        ),
    ]
